### ISSUE TITLE
PHP Memory Exhaustion Errors

### ISSUE THREAD

**Issue by MufengNiu** [HughCraig/GHAP#291]
We're experiencing PHP memory exhaustion errors on the production site. This could led to apache crashes and unexpected behavior.

<img width="1293" alt="Screenshot 2023-10-20 at 16 43 55" src="https://github.com/HughCraig/GHAP/assets/51284623/859f4731-49ff-4502-bf01-24c3fa7ef3a1">

**Comment by yangli0516** [comment]
@MufengNiu , can you state the original memory limit and the new value you set?

**Comment by MufengNiu** [comment]
php.ini was set to an unlimited value of -1, but the ghap project has a set of 2048 MB.  Shall we increase it to 4 GB or unlimited?
<img width="598" alt="Screenshot 2023-10-20 at 16 54 49" src="https://github.com/HughCraig/GHAP/assets/51284623/6d59c903-fb9e-42f5-9726-a032683109f4">

**Comment by yangli0516** [comment]
It seems 2048M already a large enough number. Are you able to find the request page which cause the memory exceeded error?

**Comment by MufengNiu** [comment]
@yangli0516  The search result page.
<img width="1479" alt="Screenshot 2023-10-20 at 17 14 18" src="https://github.com/HughCraig/GHAP/assets/51284623/88b75e6f-8404-479d-8dbc-73bec79e6791">

**Comment by yangli0516** [comment]
I see a lot of requests sent programmatically from "python-requests". @kainedusher , are these search requests from STMetrics.

**Comment by kainedusher** [comment]
> I see a lot of requests sent programmatically from "python-requests". @kainedusher , are these search requests from STMetrics.

I have not started deployment of STMetrics yet.

**Comment by IanMcCrabb** [comment]
@BillPascoe any insights?  Otherwise, we observe...

**Comment by yangli0516** [comment]
These requests from python seem to be legit requests as they are searching places to output JSON results.

Normally, PHP memory issue won't make the server or Apache stops. Instead, it's a layer of protection to prevent the physical memory to be exhausted when there are too many concurrent requests. Therefore, PHP's max memory limit should be set to a reasonable size (instead of setting it to the largest) to handle concurrent requests.

In our case, it seems that someone used the GHAP search API from Python to send certain number of requests at the same time for the server to handle. Also, these searches seem to be quite broad which means each request took larger memory to hold the results. Eventually, the physical memory exhausted and made the Apache stop.

We may keep an eye on this for a while to see if it happens again. In the meantime, we may consider the API throttling options to mitigate these kinds of issues.

**Comment by BillPascoe** [comment]
Try checking if this is something that simply happens if someone puts in a search that returns a very large result. Eg: do not put any search terms in GHAP search, and simply click the search button. This URL will perform such a search: https://ghap.tlcmap.org/places?searchausgaz=on&searchncg=on&searchpublicdatasets=on
This would try to retrieve all records, and it gives me web page HTTP ERROR 500. Check if causes triggers those errors in the logs.
In the past I think we had a max record limit that was slow but did not time out with error.
Now that we get the error I suspect lack of limit may be causing PHP memory errors.
If this is the cause, please apply a suitable limit on results returned. I'm not sure what it would be, so just test a few figures. I'm guessing 100,000 records? We should try to allow for big numbers, as some people may want to access very large datasets as JSON etc for analysis.

**Comment by MufengNiu** [comment]
Have increased the php memory limit and set a max limit for places on the search page.
