### ISSUE TITLE
Allow Location

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/GHAP#401]
Allow location is working fine for me but not for Hugh:

I can’t get the Allow Location prompt on my browser (Chrome). See below – I have disallowed location in Chrome (pip is crossed out in top bar) but still no prompt to allow. (I have allowed location in Windows meanwhile.

![image](https://github.com/user-attachments/assets/250deac3-e23c-4209-8a83-7ea611fa2776)

**Comment by MufengNiu** [comment]
Please click on the Location icon in the URL bar and set to 'Continue allowing this site to access your location', the prompt will not show when set to 'always block location from this site' (Browser we cannot change this).

<img width="808" alt="Screenshot 2024-07-17 at 08 48 05" src="https://github.com/user-attachments/assets/08dcdf9a-cdda-4749-b392-36a94cc049bf">

<img width="32" alt="Screenshot 2024-07-17 at 08 48 02" src="https://github.com/user-attachments/assets/9bb63f3d-2fbc-4d6a-bd17-6e76d7e40f5d">

**Comment by IanMcCrabb** [comment]
@HughCraig does the above response from Mufeng work for you.

**Comment by HughCraig** [comment]
Yes, thanks, that is clear.
However, with Chrome I still don't get the expected behaviour. If I have Allow switched off in Windows, and Allow switched on in Chrome, I don't get a popup on the TLCMap test site and the view is (unexpectedly) centred on my location.
If I use Microsoft Edge things work as expected: if I have Allow switched off in Windows I do get a popup, and if I don't Allow (i.e.,Block) in TLCMap I get the view of Australia as a whole.

**Comment by IanMcCrabb** [comment]
OK, we might need to do some more refinement on this as the feature is dependant on the browser

**Comment by IanMcCrabb** [comment]
@MufengNiu I think we can run with it as it is for the moment and pick this up again once we get feedback from stakeholder in a week or so.
